### PR TITLE
Upgrades version of Stripe Checkout 

### PR DESCRIPTION
**Pull request by ribordy**
This takes users off-domain to complete their payment, then sends them back to the donation page with a confirmation shown when they return after completing their payment.

https://www.loom.com/share/7a3cec28f01e42e393c08a017b1af141

### CODE REVIEW

**Comment by mojowen** [comment]
@ribordy should be able to fix the lint issues if you run `npm run fix`

**Comment by mojowen** [comment]
Just merged @pramodthammaiah's work - so the webhook should be live shortly https://github.com/pizza-to-the-polls/pizzabase/pull/25

**Comment by mojowen** [comment]
This is working great for me in the test env

**Comment by ribordy** [comment]
Awesome! So if we merge this in, we can have the end-to-end flow up on next to test it?

**Comment by mojowen** [comment]
Oh it's live right now - test away! http://next.polls.pizza/

**Comment by ribordy** [comment]
Yeah, looks like there's a bug with it--lemme check it out and fix.

**Comment by ribordy** [comment]
Oh hm, I think maybe working across multiple envs left my stripe cookies in a weird spot. Confirmed it's working in a private window!

**Comment by mojowen** [comment]
@ribordy nice - it was working well for me too. And confirmed the new webhook is good - let's ship it

**Review by mojowen — APPROVED** [review]

**Comment by mojowen** [comment]
I'll let you do the honors

**Comment by ribordy** [comment]
:raised_hands: Awesome! I'll be reachable if any issues arise over the weekend.

**Comment by mojowen** [comment]
@ribordy thank you so much for your help and getting this in before the big weekend!

**Pull request merged**
